### ISSUE TITLE
reverse_image_search：docker无法下载模型的问题

### ISSUE THREAD

**Issue by 1344265305** [milvus-io/bootcamp#1069]
在搭建以图搜图系统时，参考https://github.com/milvus-io/bootcamp/tree/master/solutions/reverse_image_search/quick_deploy

在用docker-compose搭建好容器后，进入以图搜图网址，输入data/后点“+” ，img-search-webserver自动下载torch，opencv等库，随后不停输出Loading pretrained weights。使用stats查看后发现没有流量；查看代码应该是下载没有开始；
![屏幕截图 2022-09-06 155044](https://user-images.githubusercontent.com/102736689/188579888-6c1ab250-6a98-4e70-ba98-c23827bc14f3.png)

**Comment by shiyu22** [comment]
Hi @1344265305, can you try fewer images? For example, 10~20, first check whether your deployment is successful.

It shows that `Extracting ... No.70, 17125 images intotal`, so I think the webserver is processing the image data. And it's confusing that always prints loading model, maybe because fastAPI is async, you can check your memory changes.

**Comment by 1344265305** [comment]
> 

感谢您的回复

> Hi @1344265305, can you try fewer images? For example, 10~20, first check whether your deployment is successful.
> 
> It shows that `Extracting ... No.70, 17125 images intotal`, so I think the webserver is processing the image data. And it's confusing that always prints loading model, maybe because fastAPI is async, you can check your memory changes.
