### ISSUE TITLE
[feature request] docker / as a service for the recommender system

### ISSUE THREAD

**Issue by x0rzkov** [milvus-io/bootcamp#252]
Hi guys,

Hope you are all well !

I found on medium your article https://medium.com/unstructured-data-service/how-xiaomi-browser-uses-milvus-to-build-its-news-recommender-system-62fb27ba42e4, and I wanted to give a try to milvus but I could not find a restful server in the repository.

In a nutshell, I am looking for something like machinebox released in another medium article https://blog.machinebox.io/introducing-suggestionbox-personalization-and-recommendation-machine-learning-in-a-docker-b9d69f937716

Is it possible to update the recommender system so It can work as a service with flask ?

Thanks in advance for your replies and insights about that.

Cheers,
X

**Comment by shiyu22** [comment]
Hello,

Hope you are well!

Of course, you can use Milvus for applications such as machinebox. And Milvus provides Restful service, you can refer to https://github.com/milvus-io/milvus/tree/master/core/src/server/web_impl

The recommendation system solution under Milvus-bootcamp is implemented using Milvus (similarity vector search engine), so you can see it is just a demo or in order to guide you how to apply Milvus in more scenarios. And we are not planning to add docker/flask service for it. But Milvus is complete, for more information, see https://www.milvus.io/

In your article about machinebox, I learned that the system extracts text into feature vectors, and then uses Milvus to process these feature vectors, so I believe Milvus will be easy to use.

Hope you enjoy your time with Milvus.

Sincerely,
Your friend

**Comment by x0rzkov** [comment]
Hi,

Thanks for the reply very much !

What I am missing are the steps as described in machineboxarticle article, as I would like to understand how to create/train the model, then to add users preferences to tweak the responses then to query the database.

Is it possible to write such tutorial with all the steps ?

Nb. I wrote paper2code.com in golang so I would like to write the client in golang. Would be awesome to provide more advanced example to the golang sdk. ^^

Cheers,

**Comment by shiyu22** [comment]
Hi,

Regarding how to build a training model for the recommendation system, we usually use open source models instead of training ourselves(such as paddlepaddle, bert, etc), because Milvus is focusing on vector retrieval. So you can learn more about these AI models.

Milvus has Go sdk too, you can refer to https://github.com/milvus-io/milvus-sdk-go

**Comment by lucmichalski** [comment]
Thanks for the ref, I already installed the go-sdk.

Can you make a tutorial with the rest api with an open source model ?

**Comment by shiyu22** [comment]
Yes we have a tutorial about image search with VGG model, of course it used the flask, you can see the code at https://github.com/milvus-io/bootcamp/tree/master/solutions/pic_search/webserver

**Comment by JackLCL** [comment]
他g72会&nbsp;


---Original---
