### ISSUE TITLE
docker run -td -p 19530:19530 -p 8080:8080 -v /milvus/db:/opt/milvus/db -v /milvus/conf:/opt/milvus/conf -v /milvus/logs:/opt/milvus/logs milvusdb/milvus

### ISSUE THREAD

**Issue by Jie-Yuan** [milvus-io/bootcamp#51]
130ebd813b844f2e41e2d2f89929b64a06618926762a9dc7435bfb70d5ce17da
docker: Error response from daemon: Mounts denied:
The paths /milvus/logs and /milvus/conf and /milvus/db
are not shared from OS X and are not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.

**Comment by lym777** [comment]
Docker for Mac volume mounts behave differently than the base Docker system. This is mostly because Docker tries to comply with Apple's filesystem sandbox guidelines.
As shown in Docker's preferences, only certain paths are exported by macOS.
/Users
/Volumes
/tmp
/private

In addition, I suggest you use milvus in linux. We have not tested milvus in mac.
