### ISSUE TITLE
Install milvus2.0.0 version, download hello_milvus.py, prompt the following error message

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#569]
![image](https://user-images.githubusercontent.com/78945582/127815318-0561e43e-c827-425c-842f-81beb3ccd5b8.png)

wget https://raw.githubusercontent.com/milvus-io/pymilvus-orm/v2.0.0rc2/examples/hello_milvus.py

**Comment by shiyu22** [comment]
Which version of Milvus 2.0.0 are you using, rc1 or rc2? You need to note the version correspondence between pymilvus-orm and Milvus, as well as hello_milvus.py.

If it's not an issue about the version, it may be a Milvus bug and you can submit an issue to [milvus](https://github.com/milvus-io/milvus/issues) project instead of Bootcamp.

**Comment by shiyu22** [comment]
not activate, closed.
