### ISSUE TITLE
Milvus2.0.0, add break point at the position shown in the picture, it can’t stop when loading the picture 

### ISSUE THREAD

**Issue by lixiangMindSpore** [milvus-io/bootcamp#576]
![image](https://user-images.githubusercontent.com/78945582/127994421-7a22b834-a75a-4fe3-859a-23dcabf3c882.png)

**Comment by ss892714028** [comment]
First of all, Please use the issue template to submit an issue, the community needs information to reproduce your issue. I will answer it this time but please do remember to use the template in the future.

Here is the template, you should have seen this when you submitted the issue.

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior(Docker or Source code):
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See an error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Software version (please complete the following information):**
 - Milvus: [e.g. 2.0.0rc1]
 - Server: [e.g. 2.0.0]
 - Client: [e.g. 2.0.0]


**Additional context**
Add any other context about the problem here.

================================================================
Answer below:

This is a http request, you cannot pass parameter as it is a python method. You can write a new method, a main() function for instance, and call this function within the new method, that way you can add breakpoint.

**Comment by shiyu22** [comment]
not activate, closed.
