### ISSUE TITLE
[BUG]: 当milvus容器重启后, 搜索相似图片会失败一直卡着

### ISSUE THREAD

**Issue by bk757** [milvus-io/bootcamp#856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

按教程搭建以图搜图Demo成功，实现加载图片和搜索功能；

当milvus docker容器重启后，搜索功能就不成功了。

### Expected Behavior

1、milvus docker容器没重启之前功能正常：
![image](https://user-images.githubusercontent.com/22384214/139257250-40aa2e41-d558-422f-980a-8309f4779f09.png)

2、停止容器再启动
![22ED8266-403E-48ac-B66F-97E25D1FEE8B](https://user-images.githubusercontent.com/22384214/139258704-7d76a09c-a483-4602-98f8-902909590986.png)

![7CF0C292-B4C8-4054-89F5-5C67F5FC2FD6](https://user-images.githubusercontent.com/22384214/139258758-8a2f7517-e6ce-448d-a0ca-6133c8a2378d.png)

搜索失败，有知道是什么问题或者这么解决的吗？

### Steps To Reproduce

```markdown
cd milvus
docker-compose stop
docker-compose start
```

### Software version

```markdown
Milvus: [e.g. 2.0.0rc7]
Server: [e.g. 2.0.0]
Client: [e.g. 1.0.0]
```

**Comment by shiyu22** [comment]
The error in the picture caused by the Milvus service cannot be connected, or the version of pymilvus and Milvus does not correspond.

As for the issue of reverse images search solution, I think this is indeed a bug. Because Milvus must load before a search, in fact, we will [load after we insert data](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/quick_deploy/server/src/milvus_helpers.py#L67). It's just that you restarted Milvus, so need to reload it.

Thanks for your good first issue :)
To fix this bug, you only need to add a loading interface before [searching](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/quick_deploy/server/src/milvus_helpers.py#L108). Can you update the code and submit a PR to become our contributor?
