### ISSUE TITLE
Can't add a single picture into the milvus, the file name does not support Chinese characters

### ISSUE THREAD

**Issue by tanst** [milvus-io/bootcamp#981]
Can't add a single picture into the milvus, the file name does not support Chinese characters

**Comment by ss892714028** [comment]
> Can't add a single picture into the Milvus, the file name does not support Chinese characters

Thank you for your interest in Milvus Bootcamp.
First of all, this issue contains two issues, please open another issue for the support for Chinese characters.

Do you mean that you want the Load API to take an image instead of a directory of images? 
You can simply modify operations/load.py to check whether the input is an image or image_directory before creating embedding.

```python
def extract_features(img_dir, model):
    try:
        cache = Cache('./tmp')
        feats = []
        names = []
        img_list = get_imgs(img_dir)
        total = len(img_list)
        cache['total'] = total
        #check if img_dir is a image or image_path
        #if it is image, create embedding and return, else, traverse the directory
        for i, img_path in enumerate(img_list):
            #extract feature
        return feats, names
    except Exception as e:
        LOGGER.error(f"Error with extracting feature from image {e}")
        sys.exit(1)
```

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
