### ISSUE TITLE
[BUG]: ValueError: shiyu/img_object_embedding_pytorch_yolov5_resnet50 repo doesnt exist.

### ISSUE THREAD

**Issue by jiamjg** [milvus-io/bootcamp#985]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Downloading Pipeline: img_object_embedding_pytorch_yolov5_resnet50
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    MODEL = CustomOperator()
  File "/app/src/encode.py", line 17, in __init__
    self.yolo_embedding = pipeline('shiyu/img_object_embedding_pytorch_yolov5_resnet50')
  File "/usr/local/lib/python3.7/site-packages/towhee/__init__.py", line 175, in pipeline
    yaml_path = _download_pipeline(cache_path, task, force_download=force_download)
  File "/usr/local/lib/python3.7/site-packages/towhee/__init__.py", line 135, in _download_pipeline
    download_repo(author, repo, branch, str(repo_path))
  File "/usr/local/lib/python3.7/site-packages/towhee/utils/hub_tools.py", line 411, in download_repo
    raise ValueError(user + '/' + repo + ' repo doesnt exist.')
ValueError: shiyu/img_object_embedding_pytorch_yolov5_resnet50 repo doesnt exist.

### Expected Behavior

The file named 'shiyu/img_object_embedding_pytorch_yolov5_resnet50' can download successfully.
The img-obj-det-webserver can run normally.

### Steps To Reproduce

```markdown
cd ./solutions/reverse_image_search/object_detection
docker-compose up -d
docker logs img-obj-det-webserver
```

### Software version

```markdown
Milvus: 0.2.0
```

**Comment by shiyu22** [comment]
Sorry, this error is caused by the updating of the [Towhee](https://github.com/towhee-io/towhee). The error is reported because Towhee modified the pipeline. You can modify the code of [encode.py](https://github.com/milvus-io/bootcamp/blob/master/solutions/reverse_image_search/object_detection/server/src/encode.py#L17) to `self.yolo_embedding = pipeline('towhee/img_object_embedding')` and run the server through the source code.

**Comment by shiyu22** [comment]
This issue has not had recent activity, and it will be closed if no further activity occurs.
